export const LOADING = 'LOADING'; // 用于页面和区块的加载中状态。
export const MODAL = 'MODAL'; // 用于对话框是否可见
export const REQ_SYS_DICT_SUCCESS = 'REQ_SYS_DICT_SUCCESS'; // 根据字典代码获取字典列表
export const REQ_ENTER_DICT_SUCCESS = 'REQ_ENTER_DICT_SUCCESS'; // 根据字典代码,企业编码获取字典列表
export const CLEAR_ENTER_DICT_SUCCESS = 'CLEAR_ENTER_DICT_SUCCESS'; // 清空字典值
export const OSS_CLIENT_SUCCESS = 'OSS_CLIENT_SUCCESS'; // 获取OSS client
export const OSS_UPLOAD_SUCCESS = 'OSS_UPLOAD_SUCCESS'; // OSS文件上传成功
export const FILE_LIST_SUCCESS = 'FILE_LIST_SUCCESS'; // 已上传文件列表
export const SAVA_CITIESID = 'SAVA_CITIESID'; // 保存多级联动多选支持城市
export const SAVA_INDUSTRY = 'SAVA_INDUSTRY'; // 保存多级联动多选受众行业
export const INSERT_CUST_SUCCESS = 'INSERT_CUST_SUCCESS'; // 客户信息批量导入成功
export const EMPTY_CITY_IND = 'EMPTY_CITY_IND'; // 清空支持城市、受众行业